// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAON-tefxT2atHoT0XRxXjIYhwOsBGviFc',
    appId: '1:951539541124:web:158314fa2251dde4a84ed1',
    messagingSenderId: '951539541124',
    projectId: 'quranapp-cf862',
    authDomain: 'quranapp-cf862.firebaseapp.com',
    storageBucket: 'quranapp-cf862.firebasestorage.app',
    measurementId: 'G-5ECXV7449H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBai67CF3H10ASKAQew5h7t2okonS42edk',
    appId: '1:951539541124:android:7bc221739423f079a84ed1',
    messagingSenderId: '951539541124',
    projectId: 'quranapp-cf862',
    storageBucket: 'quranapp-cf862.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLWKRnLvhXpmTf2b95OrXkiNV3tJsXBY',
    appId: '1:951539541124:ios:e40fe3abe1682e0da84ed1',
    messagingSenderId: '951539541124',
    projectId: 'quranapp-cf862',
    storageBucket: 'quranapp-cf862.firebasestorage.app',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLWKRnLvhXpmTf2b95OrXkiNV3tJsXBY',
    appId: '1:951539541124:ios:e40fe3abe1682e0da84ed1',
    messagingSenderId: '951539541124',
    projectId: 'quranapp-cf862',
    storageBucket: 'quranapp-cf862.firebasestorage.app',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAON-tefxT2atHoT0XRxXjIYhwOsBGviFc',
    appId: '1:951539541124:web:3cda25c3629f0a56a84ed1',
    messagingSenderId: '951539541124',
    projectId: 'quranapp-cf862',
    authDomain: 'quranapp-cf862.firebaseapp.com',
    storageBucket: 'quranapp-cf862.firebasestorage.app',
    measurementId: 'G-TNLJK9JJHS',
  );
}
